# Generated by Django 5.2.16 on 2026-07-25 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=3, unique=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=3, unique=True)),
            ],
            options={
                "verbose_name_plural": "cities",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("flight_number", models.CharField(max_length=10)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flights",
                        to="reservations.airline",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arriving_flights",
                        to="reservations.city",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departing_flights",
                        to="reservations.city",
                    ),
                ),
            ],
            options={
                "ordering": ["departure_time", "airline__code", "flight_number"],
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("seat_number", models.CharField(max_length=5)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="reservations.flight",
                    ),
                ),
            ],
            options={
                "ordering": ["flight", "seat_number"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("guest_name", models.CharField(blank=True, max_length=100)),
                ("guest_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="reservations.seat",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="flight",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin", models.F("destination")), _negated=True),
                name="flight_origin_destination_differ",
            ),
        ),
        migrations.AddConstraint(
            model_name="flight",
            constraint=models.CheckConstraint(
                condition=models.Q(("arrival_time__gt", models.F("departure_time"))),
                name="flight_arrival_after_departure",
            ),
        ),
        migrations.AddConstraint(
            model_name="flight",
            constraint=models.UniqueConstraint(
                fields=("airline", "flight_number", "departure_time"),
                name="unique_scheduled_flight",
            ),
        ),
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.UniqueConstraint(
                fields=("flight", "seat_number"), name="unique_seat_per_flight"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(fields=("seat",), name="unique_booking_per_seat"),
        ),
    ]
