# Generated by Django 5.2.16 on 2026-07-25 15:11

import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False),
                    models.Q(
                        django.db.models.lookups.GreaterThan(
                            django.db.models.functions.text.Length(
                                django.db.models.functions.text.Trim("guest_name")
                            ),
                            0,
                        ),
                        django.db.models.lookups.GreaterThan(
                            django.db.models.functions.text.Length(
                                django.db.models.functions.text.Trim("guest_email")
                            ),
                            0,
                        ),
                    ),
                    _connector="OR",
                ),
                name="booking_has_user_or_guest_details",
            ),
        ),
    ]
